export const FETCH_TOP_SALES_CLEAR = 'FETCH_TOP_SALES_CLEAR';
export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';

export const FETCH_CATALOG_CATEGORIES_REQUEST = 'FETCH_CATALOG_CATEGORIES_REQUEST';
export const FETCH_CATALOG_CATEGORIES_CHANGE = 'FETCH_CATALOG_CATEGORIES_CHANGE';
export const FETCH_CATALOG_CATEGORIES_SUCCESS = 'FETCH_CATALOG_CATEGORIES_SUCCESS';
export const FETCH_CATALOG_ITEMS_REQUEST = 'FETCH_CATALOG_ITEMS_REQUEST';
export const FETCH_CATALOG_ITEMS_MORE = 'FETCH_CATALOG_ITEMS_MORE';
export const FETCH_CATALOG_ITEMS_SUCCESS = 'FETCH_CATALOG_ITEMS_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';

export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

export const FETCH_PRODUCT_CLEAR = 'FETCH_PRODUCT_CLEAR';
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const BASKET_INIT_PRODUCT = 'BASKET_INIT_PRODUCT';
export const BASKET_CHANGE_PRODUCT = 'BASKET_ADD_PRODUCT';

export const SEND_ORDER_INIT = 'SEND_ORDER_INIT';
export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';
